Issue 1591 - Add support to send chunk info in JSON format with each …
FineUploader/fine-uploader pull request #1597
Opened 2016-06-22 15:55 UTC by krraghavan

## Brief description of the changes [REQUIRED]
This PR allows clients to use the onUploadChunk callback method to customize the payload sent with each chunk (Issue 1591)

## What browsers and operating systems have you tested these changes on? [REQUIRED]
IE11, Safari, Firefox, Chrome

## Are all automated tests passing? [REQUIRED]
Local build succeeded.

## Is this pull request against develop or some other non-master branch? [REQUIRED]
No

…chunk

2016-06-22 15:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FineUploader/fine-uploader?pullRequest=1597) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FineUploader/fine-uploader?pullRequest=1597) before we can accept your contribution.<br/><hr/>**Kollivakkam Raghavan (rkolliva)** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2016-07-13 22:34 UTC, rnicholus commented
It looks like you ran into some issues while implementing this. Do you have plans to continue your work?

2016-07-13 22:57 UTC, krraghavan commented
No I am using my fork in our project. Works great. Have to fix unit tests. Will do that in the next week or so and get back to you. My changes broke the unit tests and I'll also look to add more for my changes
Thx for following up
Raghavan. 

Please pardon my brevity and any typos as this mail is sent from my mobile device

> On Jul 13, 2016, at 3:34 PM, Ray Nicholus <notifications@github.com> wrote:
> 
> It looks like you ran into some issues while implementing this. Do you have plans to continue your work?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-10-08 19:17 UTC, krraghavan commented
Hi Ray - is there anything more you need from me before you merge this in?

2016-10-09 03:28 UTC, rnicholus commented
Sorry for the delay. I still need to spend some time looking into your proposed changes and running some manual regression tests cross-browser. Also, unit tests and documentation will need to be written. There are a number of other issues and tasks in the queue ahead of this one at the moment, and I'll be on vacation for a couple weeks. I'll try to get to this as soon as reasonably possible, but I don't have a date for you at this time.

2016-12-06 20:27 UTC, rnicholus requested changes
A couple things:

1. What exactly is a "chunk ID"?
2. Can you add unit tests & documentation?

2016-12-06 20:27 UTC, rnicholus commented on client/js/uploader.basic.js
> +                chunkInfoParamName: "qqchunkinfo"
I'd like to keep these params alphabetically ordered.

2017-11-06 04:36 UTC, rnicholus commented
closing as abandoned

2017-11-06 04:36 UTC, closed without merging