Issue #1: Allow upload with empty file
FineUploader/fine-uploader pull request #1710
Opened 2017-01-05 16:05 UTC by adrianchung

## Brief description of the changes [REQUIRED]
Implement issue #903 . Allow uploading of 0 byte files. Enhancement on pull request https://github.com/FineUploader/fine-uploader/pull/1673

## What browsers and operating systems have you tested these changes on? [REQUIRED]
Chrome 55.0.2883.95 (64-bit) on OSX 10.11.6

## Are all automated tests passing? [REQUIRED]
yes

## Is this pull request against develop or some other non-master branch? [REQUIRED]
yes

2017-01-05 16:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FineUploader/fine-uploader?pullRequest=1710) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FineUploader/fine-uploader?pullRequest=1710) before we can accept your contribution.<br/>

2017-01-05 17:39 UTC, rnicholus requested changes
Looks good, other than my one question. Also, could you write some unit tests that exercise `allowEmpty: true`?

2017-01-05 17:39 UTC, rnicholus commented on client/js/uploader.api.js
> +            if (total === 0 || Math.round(loaded / total * 100) === 100) {
Why was this added? It's not clear to me what consequences are associated with this change.

2017-01-05 19:07 UTC, achung-miovision commented on client/js/uploader.api.js
> +            if (total === 0 || Math.round(loaded / total * 100) === 100) {
When files are uploading you see a progress bar, but if there's no bytes to upload then we're technically done, so we need to hide the rest of the icons

2017-01-05 19:08 UTC, achung-miovision commented
Unit tests have been added. I'm not sure what the CLA is for as I'm split between two github accounts right now and I've signed it on both. If it's a problem I can dig further to see what's happening there.

2017-01-05 19:16 UTC, rnicholus commented on test/unit/uploader.basic.api.js
> +                .then(function() { assert.fail(); }, function() {});
This (and the subsequent test) do not look valid. As far as I can tell, the test will exit before the promise is resolved. This is effectively an async test. You'll need to make use of the `done` function in both tests.

In the first test, in the second function (failure), add a call to `done`. In the second test, add a call to `done` in the first `then` function (success).

2017-01-05 20:01 UTC, rnicholus commented on test/unit/uploader.basic.api.js
> +                .done(function() { assert.equal(-1, result); });
I would suggest reverting these changes and making use of the `done` function instead. You can use this test as an example: https://github.com/adrianchung/fine-uploader/blob/40db9e3652ea73cf13d7d5244a3336994afb88a5/test/unit/uploader.basic.api.js#L195

2017-01-05 20:03 UTC, adrianchung commented on test/unit/uploader.basic.api.js
> +                .done(function() { assert.equal(-1, result); });
I decided to leverage the failed callback here to set the result. fine uploader seems to have its own promise implementation, so I can't actually call done(); from without the success/failure callbacks. I flipped the values and verified that the tests pass as expected.

2017-01-05 20:17 UTC, achung-miovision commented on test/unit/uploader.basic.api.js
> +                .done(function() { assert.equal(-1, result); });
Oh I see, I was confused between promise done() and mocha async done for when the test completes.. updated as requested.

2017-01-05 20:22 UTC, rnicholus commented on test/unit/uploader.basic.api.js
> +                .done(function() { assert.equal(-1, result); });
Not sure I follow. You can (and should) call `done` inside of either the failure or the success `then` callbacks. The tests are likely passing as the tests are exiting prematurely. Promises are asynchronous operations, and your tests are written as if they were synchronous.

2017-01-05 20:24 UTC, adrianchung commented on test/unit/uploader.basic.api.js
> +                .done(function() { assert.equal(-1, result); });
Please ignore this comment. I understand what you mean now that I've looked up your example and your mocha reference properly

2017-01-05 21:46 UTC, rnicholus approved these changes

2017-01-05 21:50 UTC, rnicholus commented
I'll just run a few quick manual tests sometime in the next few days or so. If all looks good, I'll release this as 5.12.0. Thanks for your work on this!

2017-01-06 22:37 UTC, merged

2017-01-06 22:38 UTC, rnicholus commented
This has been merged into develop. I hope to release v5.12.0 this weekend. Thanks again!