feat(uploader.api.js) added `id` and `uuid` to `showConfirm()`
FineUploader/fine-uploader pull request #1750
Opened 2017-02-13 00:02 UTC by nalbion

## Brief description of the changes
Added `id` and `uuid` to `showConfirm()`.  I personally have 2 reasons for this:

- I want the $mdDialog to animate from the button which was pressed
- I do virus scanning on upload files and when a user presses "delete" for a file which has been rejected, I don't want the confirm dialog to be shown

## What browsers and operating systems have you tested these changes on? 
N/A

## Are all automated tests passing? 
yes

## Is this pull request against develop or some other non-master branch? 
develop

2017-02-13 00:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FineUploader/fine-uploader?pullRequest=1750) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FineUploader/fine-uploader?pullRequest=1750) before we can accept your contribution.<br/><hr/>**Nicholas Albion** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-02-13 01:29 UTC, rnicholus commented
Thanks for the PR! I'll take a closer look as soon as I get a chance, but I would suggest you remove the UUID parameter. It's redundant and can be determined given an ID using the [`getUuid()` method](http://docs.fineuploader.com/branch/master/api/methods.html#getUuid).

2017-02-13 03:15 UTC, rnicholus requested changes

2017-02-13 03:15 UTC, rnicholus commented on client/js/uploader.api.js
> +            retVal = this._options.showConfirm(confirmMessage, id, uuid);
Please remove `uuid` since this can be obtained via the `getUuid()` API method. Also please update the docs after this change.

2017-02-13 07:18 UTC, nalbion commented
Hi @rnicholus, `getUuid()` could be used to get the uuid, but it's available when `showConfirm()` is called, and I need to use the value.

2017-02-13 14:23 UTC, rnicholus commented
You may need both parameters, but others may not. For consistency, please stick to the single ID parameter.

2017-02-13 22:56 UTC, nalbion commented on client/js/uploader.api.js
> +            retVal = this._options.showConfirm(confirmMessage, id, uuid);
done

2017-02-15 16:54 UTC, rnicholus approved these changes

2017-11-08 16:35 UTC, closed without merging