Patch / Fix for https://github.com/FineUploader/fine-uploader/issues/1172
FineUploader/fine-uploader pull request #1964
Opened 2018-01-21 09:27 UTC by galvinhsiu

## Brief description of the changes
Fix for the long standing issue on uploading using chunking,
 this usually kicked in when uploading very large files to S3 (1+
 gigabytes).  This patch alleviates the need to inflate the autoretry attempt number to be huge number, which may have ramifications on the end user.

The change is on a successful upload chunk, if autoretry is turned on and the upload is not cancelled or paused to reset the autoretry counter to 0 for the given upload handle.

Please refer to:
(https://github.com/FineUploader/fine-uploader/issues/1172).

Recommendations / comments are welcome.
## What browsers and operating systems have you tested these changes on?
{example: Safari on iOS 9.1.0 and IE11 on Windows 8.1}

Safari on Mac Sierra
< Firefox 50, > Firefox 50 on Mac Sierra
IE11 on Windows 10 / 8
Edge 14, Edge 15+ on Windows 10

## Have you written unit tests? If not, explain why.
Yes, see attached code.

2018-01-22 05:25 UTC, rnicholus requested changes
Looks pretty good, but if you could address my two comments...

2018-01-22 05:25 UTC, rnicholus commented on test/unit/chunked-uploads.js
> +            assert.expect(6 + (expectedChunks * 17) + (expectedChunks * 6), done);
I'll admin I wish I hadn't added the ability to track asserts like this - it has become a maintenance mess. I ask you do one of two things here:

Either heavily comment this line to explain the significance of this number, or rewrite this test (possibly breaking it into smaller ones) such that assert counting is no longer needed.

2018-01-22 05:25 UTC, rnicholus commented on client/js/uploader.basic.api.js
> +            if (!this._preventRetries[id] && this._options.retry.enableAuto && uploadData.status !== qq.status.PAUSED) {
Why would the status ever be "paused" here?

2018-01-22 09:45 UTC, galvinhsiu commented
Good feedback, ripped out the unused condition and slightly tweaked the unit test.

2018-01-24 05:50 UTC, rnicholus submitted a review, later dismissed

2018-01-24 05:50 UTC, rnicholus commented
Awesome, thanks! I'd like to get this merged in, and maybe you can do that. Let's continue our discussion on Twitter DM.

2018-01-27 02:50 UTC, merged